### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by swharden** [swharden/ROI-Analysis-Pipeline#11]
![image](https://user-images.githubusercontent.com/4165489/45458813-6a1d8e80-b6c3-11e8-8537-589027e1ca8f.png)

**Comment by swharden** [comment]
I think I fixed it! The problem was in generating the `ALL_dataRaw.csv` file in the main folder. Since I don't think we use that file anymore, I just disabled its creation. Let me know if it works for you now!.

Code changes: https://github.com/swharden/ROI-Analysis-Pipeline/commit/a165406f4924e3b2620c1b8db6ddea55df1a00bd

**Comment by shengwanhui** [comment]
Issue fixed!
