### ISSUE TITLE
suppress warning messages

### ISSUE THREAD

**Issue by swharden** [swharden/ROI-Analysis-Pipeline#3]
Can something to be done to prevent the warnings? Currently warnings I get are:

```
Attaching package: 'reshape2'

The following objects are masked from 'package:data.table':

    dcast, melt

Parsed with column specification:
cols(
  X1 = col_integer(),
  Mean1 = col_double(),
  Mean2 = col_double(),
  Mean3 = col_double(),
  Mean4 = col_double(),
  Mean5 = col_double(),
  Mean6 = col_double(),
  Mean7 = col_double()
)
Warning message:
Missing column names filled in: 'X1' [1] 
```

**Comment by beronicao** [comment]
Resolved with: 

sinkfile <- file("messages.Rout", open = "wt")
sink(sinkfile, type = "message")
... 
sink()

**Comment by swharden** [comment]
I love this! I added a piece of code that displays the contents of `messages.Rout` if it finds it. It can be seen below the images on any page after it is re-analyzed.

example: http://192.168.1.225:8080/SWHLabPHP/src/?page=roi&project=\\Spike\X_Drive\Data\SCOTT\2017-05-10%20GCaMP6f\2017-05-10%20GCaMP6f%20PFC%20OXTR%20cre\2017-05-31%20cell2

**Comment by swharden** [comment]
It looks like if there's a legitimate crash of the code, that warning is not displayed as error output. Can we reverse the change that saved all output as `messages.Rout`, and show all warnings/errors? It is nice to know immediately when the R script crashes.

Next, can we modify the code to eliminate the warnings? Warnings usually occur to warn of imperfect code or function usage. Perhaps by fixing the underlying issues that cause the warnings we can prevent them from showing so much error text...

**Comment by swharden** [comment]
we are shifting to a concise package format, so I'll revisit this after the big change...
