### ISSUE TITLE
output image formatting

### ISSUE THREAD

**Issue by swharden** [swharden/ROI-Analysis-Pipeline#4]
Add the argument `type="cairo"` to all `png()` functions to make the output nicer looking on Windows computers. This tip and others were on [this site I found](http://gforge.se/2013/02/exporting-nice-plots-in-r/). The largest advantage is that Cairo uses anti-aliasing.

Also, let's make the output width and height variables which we store at the top of the script, so we can easily change them. For now let's default to 2000x1500.  They're automatically scaled down when they're viewed on the website, but their original size is high enough quality to put on a poster.

##  Comparison
default | Cairo
---|---
![a](https://cloud.githubusercontent.com/assets/4165489/26654302/58dbeb3c-4624-11e7-830f-01f917278cd7.png) | ![b](https://cloud.githubusercontent.com/assets/4165489/26654303/5a27f814-4624-11e7-8a2d-819a6939d98d.png)

**Comment by beronicao** [comment]
Put png dimension variables at top of script: 
png.width = 2000
png.height = 1500
